apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-billing-srv
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: cp-billing-srv
      namespace: default
      labels:
        cloud-pipeline/cp-billing-srv: "true"
    spec:
      nodeSelector:
        cloud-pipeline/cp-billing-srv: "true"
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: cp-billing-srv
          image: $CP_COMMON_DISTR_DOCKER_PREFIX:billing-srv-$CP_VERSION
          imagePullPolicy: "Always"
          command: ["/init"]
          envFrom:
            - configMapRef:
                name: cp-config-global
          volumeMounts:
            - name: billing-logs
              mountPath: /opt/billing/logs
            - name: cp-cloud-credentials
              mountPath: "/root/.cloud"
              readOnly: true
      volumes:
        - name: billing-logs
          hostPath:
            path: /opt/billing/logs
        - name: cp-cloud-credentials
          secret:
            secretName: cp-cloud-credentials
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
