apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-heapster-elk
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        cloud-pipeline/cp-heapster-elk: "true"
    spec:
      nodeSelector:
        cloud-pipeline/cp-heapster-elk: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: cp-heapster-elk
          command:
          - sh
          - elasticsearch/bin/elasticsearch
          - -Ehttp.host=0.0.0.0
          image: nshou/elasticsearch-kibana:kibana5
          imagePullPolicy: "IfNotPresent"
          envFrom:
          - configMapRef:
              name: cp-config-global
          readinessProbe:
            httpGet:
              path: /
              port: 9200
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
