apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-sensitive-proxy
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        cloud-pipeline/cp-sensitive-proxy: "true"
    spec:
      nodeSelector:
        cloud-pipeline/cp-tinyproxy: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: cp-sensitive-proxy
          image: $CP_COMMON_DISTR_DOCKER_PREFIX:tinyproxy-$CP_VERSION
          imagePullPolicy: "IfNotPresent"
          command: ["/init"]
          env:
          - name: CP_TP_ALLOWED_DESTINATION
            value: .amazonaws.com,.googleapis.com,.azure.com
          envFrom:
          - configMapRef:
              name: cp-config-global
          volumeMounts:
            - mountPath: /opt/tinyproxy/logs
              name: tinyproxy-logs
      volumes:
        - name: tinyproxy-logs
          hostPath:
            path: /opt/sensitive-proxy/logs
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
