apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-git
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        cloud-pipeline/cp-git: "true"
    spec:
      nodeSelector:
        cloud-pipeline/cp-git: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: cp-git
          image: lifescience/cloud-pipeline:git-$CP_VERSION
          imagePullPolicy: "Always"
          ports:
            - containerPort: ${CP_GITLAB_INTERNAL_PORT}
          envFrom:
          - configMapRef:
              name: cp-config-global
          volumeMounts:
            - mountPath: /var/log/gitlab
              name: git-logs
            - mountPath: /var/opt/gitlab
              name: git-data
            - mountPath: /opt/gitlab/pki
              name: git-pki
            - mountPath: /opt/idp/pki
              name: idp-pki
            - mountPath: /opt/common/pki
              name: common-pki
            - mountPath: /opt/bkp-worker/cp-git
              name: bkp-worker-cp-git
          # With SSO enabled - readiness probe gets redirect to IdP and fails, switched to manual ping in install.sh
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: ${CP_GITLAB_INTERNAL_PORT}
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
      volumes:
        - name: git-logs
          hostPath:
            path: /opt/gitlab/logs
        - name: git-data
          hostPath:
            path: /opt/gitlab/data
        - name: git-pki
          hostPath:
            path: /opt/gitlab/pki
        - name: idp-pki
          hostPath:
            path: /opt/idp/pki
        - name: common-pki
          hostPath:
            path: /opt/common/pki
        - name: bkp-worker-cp-git
          hostPath:
            path: /opt/bkp-worker/cp-git
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
