apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-bkp-worker-$CP_BKP_SERVICE_NAME
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        cloud-pipeline/cp-bkp-worker: "$CP_BKP_SERVICE_NAME"
    spec:
      nodeSelector:
        cloud-pipeline/$CP_BKP_SERVICE_NAME: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: cp-bkp-worker-$CP_BKP_SERVICE_NAME
          image: lifescience/cloud-pipeline:cp-bkp-worker-$CP_VERSION
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: cp-config-global
          env:
            - name: CP_BKP_SERVICE_NAME
              value: $CP_BKP_SERVICE_NAME
            - name: CP_BKP_SERVICE_WD
              value: /opt/bkp-worker/$CP_BKP_SERVICE_NAME
          volumeMounts:
            - mountPath: /opt/bkp-worker/$CP_BKP_SERVICE_NAME
              name: bkp-wd
            - mountPath: /opt/bkp-worker/logs
              name: bkp-logs
      volumes:
        - name: bkp-wd
          hostPath:
            path: /opt/bkp-worker/$CP_BKP_SERVICE_NAME
        - name: bkp-logs
          hostPath:
            path: /opt/bkp-worker/logs
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
