apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-edge: "true"
    cloud-pipeline/role: "EDGE"
  name: cp-edge
  namespace: default
spec:
  ports:
  - protocol: TCP
    nodePort: ${CP_EDGE_INTERNAL_PORT}
    port: ${CP_EDGE_INTERNAL_PORT}
    targetPort: 8080
    name: cp-edge-port-https
  - protocol: TCP
    nodePort: ${CP_EDGE_CONNECT_INTERNAL_PORT}
    port: ${CP_EDGE_CONNECT_INTERNAL_PORT}
    targetPort: 8081
    name: cp-edge-port-connect
  type: NodePort
  selector:
    cloud-pipeline/cp-edge: "true"
