apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-edge
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        cloud-pipeline/cp-edge: "true"
        cloud-pipeline/role: "EDGE"
    spec:
      nodeSelector:
        cloud-pipeline/cp-edge: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: cp-edge
          image: lifescience/cloud-pipeline:edge-$CP_VERSION
          imagePullPolicy: "Always"
          command: ["/init"]
          env:
          - name: NODE_OPTIONS
            value: "--max_old_space_size=4096"
          envFrom:
          - configMapRef:
              name: cp-config-global
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /liveness.sh
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 4
          volumeMounts:
            - mountPath: /var/log
              name: edge-logs
            - mountPath: /opt/api/pki
              name: api-pki
              readOnly: true
            - mountPath: /opt/gitlab/pki
              name: gitlab-pki
              readOnly: true
            - mountPath: /opt/docker-registry/pki
              name: docker-pki
              readOnly: true
            - mountPath: /opt/edge/pki
              name: edge-pki
              readOnly: true
            - mountPath: /opt/common/pki
              name: common-pki
              readOnly: true
      volumes:
        - name: edge-logs
          hostPath:
            path: /opt/edge/logs
        - name: api-pki
          hostPath:
            path: /opt/api/pki
        - name: gitlab-pki
          hostPath:
            path: /opt/gitlab/pki
        - name: docker-pki
          hostPath:
            path: /opt/docker-registry/pki/
        - name: edge-pki
          hostPath:
            path: /opt/edge/pki
        - name: common-pki
          hostPath:
            path: /opt/common/pki
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
