apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-docker-registry
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        cloud-pipeline/cp-docker-registry: "true"
    spec:
      nodeSelector:
        cloud-pipeline/cp-docker-registry: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: cp-docker-registry
          image: lifescience/cloud-pipeline:registry-$CP_VERSION
          imagePullPolicy: "Always"
          ports:
            - containerPort: 443
          envFrom:
          - configMapRef:
              name: cp-config-global
          env:
          - name: REGISTRY_HTTP_ADDR
            value: "0.0.0.0:80"
          volumeMounts:
            - mountPath: /opt/docker-registry/pki
              name: docker-pki
            - mountPath: /opt/common/pki
              name: common-pki
            - mountPath: /var/lib/registry
              name: docker-images
            - mountPath: /usr/local/share/ca-certificates/cp-api
              name: docker-api-pki
            - name: cp-cloud-credentials
              mountPath: "/root/.cloud"
          # TODO: deal with 401 response from /v2/
          # readinessProbe:
          #   httpGet:
          #     path: /v2/
          #     port: 443
          #     scheme: HTTPS
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
      volumes:
        - name: docker-pki
          hostPath:
            path: /opt/docker-registry/pki
        - name: docker-images
          hostPath:
            path: /opt/docker-registry/images
        - name: docker-api-pki
          hostPath:
            path: /opt/api/pki
        - name: common-pki
          hostPath:
            path: /opt/common/pki
        - name: cp-cloud-credentials
          secret:
            secretName: cp-cloud-credentials
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
