site_name: 'Cloud Pipeline'
theme:
  name: 'readthedocs'
  custom_dir: 'custom_theme/'
docs_dir: 'md/'
extra_css:
  - 'css/extra.css'
extra_javascript:
  - 'css/extra.js'
nav:
- Introduction: 'index.md'
- Release notes:
  - v.0.13: 'release_notes/v.0.13/v.0.13_-_Release_notes.md'
  - v.0.14: 'release_notes/v.0.14/v.0.14_-_Release_notes.md'
  - v.0.15: 'release_notes/v.0.15/v.0.15_-_Release_notes.md'
  - v.0.16: 'release_notes/v.0.16/v.0.16_-_Release_notes.md'
- User guide:
  - Contents: 'manual/Cloud_Pipeline_-_Manual.md'
  - 1. Quick start: 'manual/01_Quick_start/1._Quick_start.md'
  - 2. Getting started: 'manual/02_Getting_started/2._Getting_started.md'
  - 3. Overview: 'manual/03_Overview/3._Overview.md'
  - 4. Manage Folder:
    - 4.0. Overview: 'manual/04_Manage_Folder/4._Manage_Folder.md'
    - 4.1. Create an object in Folder: 'manual/04_Manage_Folder/4.1._Create_an_object_in_Folder.md'
    - 4.2. Rename Folder: 'manual/04_Manage_Folder/4.2._Rename_folder.md'
    - 4.3. Delete Folder: 'manual/04_Manage_Folder/4.3._Delete_Folder.md'
    - 4.4. Clone a Folder: 'manual/04_Manage_Folder/4.4._Clone_a_folder.md'
    - 4.5. Lock a Folder: 'manual/04_Manage_Folder/4.5._Lock_a_folder.md'
  - 5. Manage Metadata:
    - 5.0. Overview: 'manual/05_Manage_Metadata/5._Manage_Metadata.md'
    - 5.1. Add/delete Metadata items: 'manual/05_Manage_Metadata/5.1._Add_Delete_metadata_items.md'
    - 5.2. Upload Metadata: 'manual/05_Manage_Metadata/5.2._Upload_metadata.md'
    - 5.3. Customize view of the entity instance table: 'manual/05_Manage_Metadata/5.3._Customize_view_of_the_entity_instance_table.md'
    - 5.4. Launch a Run configuration: 'manual/05_Manage_Metadata/5.4._Launch_a_run_configuration_on_metadata.md'
    - 5.5. Download data from external resources: 'manual/05_Manage_Metadata/5.5._Download_data_from_external_resources_to_the_cloud_data_storage.md'
  - 6. Manage Pipeline:
    - 6.0. Overview: 'manual/06_Manage_Pipeline/6._Manage_Pipeline.md'
    - 6.1. Create and configure Pipeline: 'manual/06_Manage_Pipeline/6.1._Create_and_configure_pipeline.md'
    - 6.1.1. Building WDL Pipeline with graphical PipelineBuilder: 'manual/06_Manage_Pipeline/6.1.1._Building_WDL_pipeline_with_graphical_PipelineBuilder.md'
    - 6.2. Launch a Pipeline: 'manual/06_Manage_Pipeline/6.2._Launch_a_pipeline.md'
    - 6.3. Delete and unregister Pipeline: 'manual/06_Manage_Pipeline/6.3._Delete_a_pipeline.md'
  - 7. Manage Detached configuration:
    - 7.0. Overview: 'manual/07_Manage_Detached_configuration/7._Manage_Detached_configuration.md'
    - 7.1. Create and customize Detached configuration: 'manual/07_Manage_Detached_configuration/7.1._Create_and_customize_Detached_configuration.md'
    - 7.2. Launch Detached configuration: 'manual/07_Manage_Detached_configuration/7.2._Launch_Detached_Configuration.md'
    - 7.3. Expansion expressions: 'manual/07_Manage_Detached_configuration/7.3._Expansion_Expressions.md'
    - 7.4. Remove Detached configuration: 'manual/07_Manage_Detached_configuration/7.4._Remove_Detached_configuration.md'
  - 8. Manage Data Storage:
    - 8.0. Overview: 'manual/08_Manage_Data_Storage/8._Manage_Data_Storage.md'
    - 8.1. Create and edit Data Storage: 'manual/08_Manage_Data_Storage/8.1._Create_and_edit_storage.md'
    - 8.2. Upload/Download data: 'manual/08_Manage_Data_Storage/8.2._Upload_Download_data.md'
    - 8.3. Create and edit text files: 'manual/08_Manage_Data_Storage/8.3._Create_and_Edit_text_files.md'
    - 8.4. Control file versions: 'manual/08_Manage_Data_Storage/8.4._Control_File_versions.md'
    - 8.5. Delete and unregister Data Storage: 'manual/08_Manage_Data_Storage/8.5._Delete_and_unregister_Data_Storage.md'
    - 8.6. Delete Files and Folders from Data Storage: 'manual/08_Manage_Data_Storage/8.6._Delete_Files_and_Folders_from_Storage.md'
    - 8.7. Create shared file system: 'manual/08_Manage_Data_Storage/8.7._Create_shared_file_system.md'
    - 8.8. Data sharing: 'manual/08_Manage_Data_Storage/8.8._Data_sharing.md'
  - 9. Manage cluster nodes: 'manual/09_Manage_Cluster_nodes/9._Manage_Cluster_nodes.md'
  - 10. Manage Tools:
    - 10.0. Overview: 'manual/10_Manage_Tools/10._Manage_Tools.md'
    - 10.1. Add and edit a Docker registry: 'manual/10_Manage_Tools/10.1._Add_Edit_a_Docker_registry.md'
    - 10.2. Add/edit a Tool group: 'manual/10_Manage_Tools/10.2._Add_Edit_a_Tool_group.md'
    - 10.3. Add a Tool: 'manual/10_Manage_Tools/10.3._Add_a_Tool.md'
    - 10.4. Edit a Tool: 'manual/10_Manage_Tools/10.4._Edit_a_Tool.md'
    - 10.5. Launch a Tool: 'manual/10_Manage_Tools/10.5._Launch_a_Tool.md'
    - 10.6. Tool security check: 'manual/10_Manage_Tools/10.6._Tool_security_check.md'
    - 10.7. Tool version menu: 'manual/10_Manage_Tools/10.7._Tool_version_menu.md'
  - 11. Manage Runs:
    - 11.0. Overview: 'manual/11_Manage_Runs/11._Manage_Runs.md'
    - 11.1. Manage runs lifecycles: 'manual/11_Manage_Runs/11.1._Manage_runs_lifecycles.md'
    - 11.2. Auto-commit Docker images: 'manual/11_Manage_Runs/11.2._Auto-commit_Docker_image.md'
    - 11.3. Sharing with other users: 'manual/11_Manage_Runs/11.3._Sharing_with_other_users_or_groups_of_users.md'
  - 12. Manage settings:
    - 12.0. Overview: 'manual/12_Manage_Settings/12._Manage_Settings.md'
    - 12.1. Add a new system event: 'manual/12_Manage_Settings/12.1._Add_a_new_system_event.md'
    - 12.2. Edit a system event: 'manual/12_Manage_Settings/12.2._Edit_a_system_event.md'
    - 12.3. Create a new user: 'manual/12_Manage_Settings/12.3._Create_a_new_user.md'
    - 12.4. Edit/delete a user: 'manual/12_Manage_Settings/12.4._Edit_delete_a_user.md'
    - 12.5. Create a group: 'manual/12_Manage_Settings/12.5._Create_a_group.md'
    - 12.6. Edit a group/role: 'manual/12_Manage_Settings/12.6._Edit_a_group_role.md'
    - 12.7. Delete a group: 'manual/12_Manage_Settings/12.7._Delete_a_group.md'
    - 12.8. Change a set of roles/groups for a user: 'manual/12_Manage_Settings/12.8._Change_a_set_of_roles_groups_for_a_user.md'
    - 12.9. Change email notification: 'manual/12_Manage_Settings/12.9._Change_email_notification.md'
    - 12.10. Manage system-level settings: 'manual/12_Manage_Settings/12.10._Manage_system-level_settings.md'
    - 12.11. Advanced features: 'manual/12_Manage_Settings/12.11._Advanced_features.md'
    - 12.12. System logs: 'manual/12_Manage_Settings/12.12._System_logs.md'
  - 13. Permissions: 'manual/13_Permissions/13._Permissions.md'
  - 14. CLI interface:
    - 14.0. Overview: 'manual/14_CLI/14._Command-line_interface.md'
    - 14.1. Install and setup: 'manual/14_CLI/14.1._Install_and_setup_CLI.md'
    - 14.2. View and manage Attributes: 'manual/14_CLI/14.2._View_and_manage_Attributes_via_CLI.md'
    - 14.3. Manage Data Storage: 'manual/14_CLI/14.3._Manage_Storage_via_CLI.md'
    - 14.4. View pipeline definitions: 'manual/14_CLI/14.4._View_pipeline_definitions_via_CLI.md'
    - 14.5. Manage pipeline executions: 'manual/14_CLI/14.5._Manage_pipeline_executions_via_CLI.md'
    - 14.6. View cluster nodes: 'manual/14_CLI/14.6._View_cluster_nodes_via_CLI.md'
    - 14.7. View and manage Permissions: 'manual/14_CLI/14.7._View_and_manage_Permissions_via_CLI.md'
    - 14.8. View tools definitions: 'manual/14_CLI/14.8._View_tools_definitions_via_CLI.md'
  - 15. Interactive services:
    - 15.0. Overview: 'manual/15_Interactive_services/15._Interactive_services.md'
    - 15.1. Starting an interactive application: 'manual/15_Interactive_services/15.1._Starting_an_Interactive_application.md'
    - 15.2. Using terminal access: 'manual/15_Interactive_services/15.2._Using_Terminal_access.md'
    - 15.3. Expose node filesystem: 'manual/15_Interactive_services/15.3._Expose_node_filesystem.md'
    - 15.4. Interactive service examples: 'manual/15_Interactive_services/15.4._Interactive_service_examples.md'
  - 16. Issues: 'manual/16_Issues/16._Issues.md'
  - 17. CP objects tagging by additional attributes: 'manual/17_Tagging_by_attributes/17._CP_objects_tagging_by_additional_attributes.md'
  - 18. Home page: 'manual/18_Home_page/18._Home_page.md'
  - Appendix A. Instance and Docker container lifecycles: 'manual/Appendix_A/Appendix_A._Instance_and_Docker_container_lifecycles.md'
  - Appendix B. Working with a Project: 'manual/Appendix_B/Appendix_B._Working_with_a_Project.md'
  - Appendix C. Working with autoscaled cluster runs: 'manual/Appendix_C/Appendix_C._Working_with_autoscaled_cluster_runs.md'
  - Appendix D. Costs management: 'manual/Appendix_D/Appendix_D._Costs_management.md'
  - Appendix E. Pipeline objects concept: 'manual/Appendix_E/Appendix_E._Pipeline_objects_concept.md'
- Cloud Pipeline API:
  - API tutorials: 'api/API_tutorials/API_tutorials.md'
  - Automation via CLI: 'api/API_tutorials/Automation_via_CLI.md'
  - Direct HTTP API implementation: 'api/API_tutorials/Direct_HTTP_API.md'
  - JavaScript example: 'api/API_tutorials/JavaScript_example.md'
